services:
  - type: web
    name: zapvenda30d
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 60 server:app
    envVars:
      - key: GEMINI_MODEL
        value: gemini-3.1-flash-lite
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
